### ISSUE TITLE
I am able to remove/add sponsors from the website

### ISSUE THREAD

**Issue by x183** [cthit/chalmers.it#109]
### 📝 Describe the bug

Hi, I am currently able to add/delete sponsors and add/remove groups through the settings page, only armIT, styrIT and maybe diigIT should be able to do this

### 🔄 To Reproduce

Log in to the webpage
Under settings you are able to modify things you shouldn't be able to

### 📷 Screenshots

![image](https://github.com/user-attachments/assets/35ed3856-e512-453b-9e32-52f54419135d)

**Comment by simon-wg** [comment]
![image](https://github.com/user-attachments/assets/da978352-610b-4344-b9b3-bbf88bb93e7b)

**Comment by simon-wg** [comment]
Nä men kollar på det om 20 min

**Comment by Oscariremma** [comment]
So this is caused by us currently having didIT as a admin group so that me and @GAsplund could have admin even tho we are not digIT any more. So this is not a bug in the code rather just that didIT currently is admin in the production deployment. Now that me and @GAsplund are styrIT and it is up and running we can probably remove didIT from the admin group list. 
![image](https://github.com/user-attachments/assets/c876a91f-8f45-4928-801c-b0e5c4511fe4)
