### ISSUE TITLE
As a nostalgic user I want to to be to search news post, so that I can find old posts easier

### ISSUE THREAD

**Issue by ViddeM** [cthit/chalmers.it#89]
### 📝 Description

Something I did relatively regularly when I studied was to search for old news posts, sometimes to find inspiration for new news posts or just to find old information. The "Current" chalmers.it has a search bar and it would be nice if the new one had that too. 

As a bonus (that I don't think is supported in the "Current" chalmers.it) it would be nice to be able to filter news post on dates (e.g. only show me news posts before/after/between selected dates).

### ✅ Acceptance Criteria

- [ ] News items are searchable

**Optional:**
 - [ ] Can filter to only show news items after a certain date (less relevant in the current ordering/display system).
 - [ ] Can filter to only show news items before a certain date (more relevant in the current ordering/display system).

**Comment by GAsplund** [comment]
We actually did have a search bar previously, but it was hidden for the pre-release due to there being no functionality. That said, I plan on getting this implemented for the real release. The addition of date range filtering is also a very nice suggestion, especially since the removal of pagination makes it very hard to read posts that are very old (imagine scrolling and manually sifting through over 1k posts!)
